#!/usr/bin/env bash

wrap_runtime_driver() {
  local dst="$1"
  local real="$2"
  local is_cxx="${3:-0}"
  local driver_name="${TRIPLE}-clang"

  if [[ "$is_cxx" == "1" ]]; then
    driver_name="${TRIPLE}-clang++"
  fi

  cat > "$dst" <<EOF
#!/usr/bin/env bash
# Wrapper to act as ${driver_name}
# Auto-generated by bootstrap.sh
set -euo pipefail

REAL_CLANG="${real}"
SYSROOT="${SYSROOT}"
TRIPLE="${TRIPLE}"
GCC_TOOLCHAIN_HINT="${GCC_TOOLCHAIN_HINT}"

ARGS=( "--target=\${TRIPLE}" "--sysroot=\${SYSROOT}" )
if [[ -n "\${GCC_TOOLCHAIN_HINT}" ]]; then
  ARGS+=( "--gcc-toolchain=\${GCC_TOOLCHAIN_HINT}" )
fi

for arg in "\$@"; do
  ARGS+=( "\$arg" )
done

exec "\${REAL_CLANG}" "\${ARGS[@]}"
EOF
  chmod +x "$dst"
}

install_runtime_wrappers() {
  SDK_USR_BIN="$SDK_ROOT/usr/bin"
  CLANG_WRAPPER="$SDK_USR_BIN/${TRIPLE}-clang"
  CLANGPP_WRAPPER="$SDK_USR_BIN/${TRIPLE}-clang++"

  mkdir -p "$SDK_USR_BIN"
  wrap_runtime_driver "$CLANG_WRAPPER" "$HOST_CLANG_BIN" 0
  wrap_runtime_driver "$CLANGPP_WRAPPER" "$HOST_CLANGPP_BIN" 1

  echo "Installed temporary runtime wrappers:"
  echo "  $CLANG_WRAPPER -> $HOST_CLANG_BIN"
  echo "  $CLANGPP_WRAPPER -> $HOST_CLANGPP_BIN"
}

stage_build_runtimes() {
  require_var BUILD_DIR
  require_var CMAKE_GENERATOR
  require_var HOST_CLANG_BIN
  require_var HOST_CLANGPP_BIN
  require_var HOST_PYTHON3
  require_var JOBS
  require_var RUNTIMES
  require_var SDK_ROOT
  require_var SRC_DIR
  require_var SYSROOT
  require_var TRIPLE

  GCC_TOOLCHAIN_HINT="${GCC_TOOLCHAIN_HINT:-}"

  stage_heading "Build target runtimes (libcxx, libcxxabi, libunwind, compiler-rt)"

  RUNTIMES_BUILD_DIR="$BUILD_DIR/runtimes-build"
  INSTALL_PREFIX="$SYSROOT/usr"

  install_runtime_wrappers

  cmake -S "$SRC_DIR/runtimes" -B "$RUNTIMES_BUILD_DIR" \
    -G "$CMAKE_GENERATOR" \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_PROJECTS="" \
    -DLLVM_ENABLE_RUNTIMES="$RUNTIMES" \
    -DLLVM_TARGETS_TO_BUILD="AArch64" \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_PREFIX" \
    -DCMAKE_SYSROOT="$SYSROOT" \
    -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
    -DCMAKE_C_COMPILER="$CLANG_WRAPPER" \
    -DCMAKE_CXX_COMPILER="$CLANGPP_WRAPPER" \
    -DPython3_EXECUTABLE="$HOST_PYTHON3" \
    -DDEFAULT_SYSROOT="$SYSROOT" \
    -DDEFAULT_TARGET_TRIPLE="$TRIPLE" \
    -DLIBCXX_ENABLE_SHARED=ON \
    -DLIBCXX_ENABLE_EXCEPTIONS=ON \
    -DLIBCXX_ENABLE_RTTI=ON \
    -DLIBCXXABI_USE_COMPILER_RT=ON \
    -DLIBCXXABI_ENABLE_SHARED=ON \
    -DLIBCXXABI_USE_LLVM_UNWINDER=ON \
    -DLIBCXX_CXX_ABI=libcxxabi \
    -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DLLVM_ENABLE_EH=ON \
    -DLLVM_ENABLE_RTTI=ON \
    -DCMAKE_C_COMPILER_TARGET="$TRIPLE" \
    -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" \
    -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld"

  cmake --build "$RUNTIMES_BUILD_DIR" --target install -j "$JOBS"

  echo "Runtimes installed to $INSTALL_PREFIX"
}
